### PR TITLE
Fixed warning about comparison of integer expressions of different si…

### LINKED ISSUE #63: warning: comparison of integer expressions of different signedness
While building 1.68.0 beta 1 on x86_64 linux cross-compiling to Windows 64 bits with mingw-w64 + g++ 8.2.0, I get this warning:
```
"x86_64-w64-mingw32-g++-8.2.0"   -I/softs/win64-mingw-8.2.0/release/iconv/include -I/softs/win64-mingw-8.2.0/release/gettext/include -I/softs/win64-mingw-8.2.0/release/bzip2/include -I/softs/win64-mingw-8.2.0/release/zlib/include -I/softs/win64-mingw-8.2.0/release/jpeg-turbo/include -I/softs/win64-mingw-8.2.0/release/xz/include -I/softs/win64-mingw-8.2.0/release/tiff/include -I/softs/win64-mingw-8.2.0/release/png/include -std=c++14 -O2 -DNDEBUG -m64 -mthreads -O3 -finline-functions -Wno-inline -Wall  -DBOOST_ALL_NO_LIB=1 -DBOOST_ASIO_NO_DEPRECATED -DBOOST_FILESYSTEM_NO_DEPRECATED -DBOOST_IOSTREAMS_USE_DEPRECATED -DBOOST_LOG_WITHOUT_EVENT_LOG -DNDEBUG  -I"." -I"/softs/win64-mingw-8.2.0/release/bzip2/include" -I"/softs/win64-mingw-8.2.0/release/zlib/include" -c -o "bin.v2/libs/iostreams/build/gcc-8.2.0/release/link-static/target-os-windows/threading-multi/mapped_file.o" "libs/iostreams/src/mapped_file.cpp"
libs/iostreams/src/mapped_file.cpp: In member function 'void boost::iostreams::detail::mapped_file_impl::try_map_file(boost::iostreams::detail::mapped_file_impl::param_type)':
libs/iostreams/src/mapped_file.cpp:324:29: warning: comparison of integer expressions of different signedness: 'boost::iostreams::stream_offset' {aka 'long long int'} and 'boost::iostreams::mapped_file_source::size_type' {aka 'long long unsigned int'} [-Wsign-compare]
             (SIZE_T) (size_ != max_length ? size_ : 0),
                       ~~~~~~^~~~~~~~~~~~~
```

### PR DESCRIPTION
**Pull request by kivadiu**
…gnedness

size_ is a stream_offset which is a boost::intmax_t which is signed
max_length is a mapped_file_source::size_type which is a std::size_t
which is unsigned

It is not expected that size_ be negative here so we cast it to the
unsigned integer.

Fixes #63

### CODE REVIEW

File: src/mapped_file.cpp [hunk 1]
```diff
@@ -323,7 +323,7 @@ void mapped_file_impl::try_map_file(param_type p)
             access,
             (DWORD) (p.offset >> 32),
             (DWORD) (p.offset & 0xffffffff),
-            (SIZE_T) (size_ != max_length ? size_ : 0), 
+            (SIZE_T) (static_cast<size_type>(size_) != max_length ? size_ : 0),
```
Comment (jeking3) [inline src/mapped_file.cpp]: I'd suggest using `boost::numeric_cast<>` so that in the event there is actually an overflow it will be handled correctly with an exception.  Otherwise looks good.

**Comment by kivadiu** [comment]
So, the new PR passed CI tests. Is it acceptable now?

**Comment by jeking3** [comment]
Yes, there are more warnings if you want to tackle them too.

https://ci.appveyor.com/project/eldiener/iostreams/build/1.0.53-develop/job/cnh2bfu25rj2yorg
